[package]
name = "remmina-to-tabby"
version = "0.1.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml_ng = "0.10.0"
uuid = { version = "1.18.1", features = ["v4"] }